name: .NET Stage - Build and Deploy

on:
  push:
    branches:
      - stage
  workflow_dispatch:
  
defaults:
    run:
        working-directory: ./backend/UpWork/
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registryrm.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4fa7439b923546e9aa178755a0077e41 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_009f8a06f57c428caf917d1085f58c97 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registryrm.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4fa7439b923546e9aa178755a0077e41 }}/upwork-api:${{ github.sha }}
        context: ./backend/UpWork/
        file: ./backend/UpWork/UpWork.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'upwork'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_04fb8e24af6e41018ed1a76a45397f4f }}
        images: 'registryrm.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4fa7439b923546e9aa178755a0077e41 }}/upwork-api:${{ github.sha }}'
