name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    defaults:
      run:
        working-directory: frontend/upwork-client
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/upwork-client/package-lock.json
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Check node version
      run: npm config list
    - name: npm clean install
      run: npm ci
    - name: npm run build
      run: npm run build --if-present
    - name: Check node version
      run: npm config list
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ANGULAR }}
